### ISSUE TITLE
Use functional components instead of Classes

### ISSUE THREAD

**Issue by Samy-33** [BitByte-TPC/resource_website#5]
It would be great to use only functional components as react hooks provide you to have state and lifecycle methods in a functional components as well. New version of react is moving towards that.

**Comment by MananJethwani** [comment]
@Samy-33 you are right that would be a great thing to go ahead with I guess this can be done easily at this stage as only sign in and sign up pages have been designed will try to asign someone to this

**Comment by MananJethwani** [comment]
@mani9896 can you research about this and would like to work on this?

**Comment by Samy-33** [comment]
Go through following resources to understand how to do this migration:  
[useState hook](https://reactjs.org/docs/hooks-state.html) for storing local state.  
[useEffect hook](https://blog.logrocket.com/lifecycle-methods-with-the-useeffect-hook/) for replacing lifecycle methods

**Comment by MananJethwani** [comment]
@mani9896 start with this....

**Comment by tushhr** [comment]
Hey @MananJethwani, can I work on this?

**Comment by MananJethwani** [comment]
sure @tushhr go ahead!!!
